-- AlterSequence
ALTER SEQUENCE "USERS_id_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "USERS" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "USERS" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
